Fix flake8
afewmail/afew pull request #297
Opened 2020-08-29 14:08 UTC by GuillaumeSeren

Hey,
so as discussed in #296 here the individual fix for the flake8 linter.

I kept one error ignored (E501) because there is a lot of them (83).

2020-08-29 15:05 UTC, flokli reviewed
LGTM, apart from a minor nit.

2020-08-29 15:41 UTC, GuillaumeSeren commented on afew/tests/test_utils.py
>  #
Ok I add that change to the branch

2020-08-29 17:07 UTC, GuillaumeSeren commented
Hey @flokli I have upgraded the branch with your feedback

2020-08-29 21:43 UTC, flokli requested changes
Please change the commit message to:

```
afew.tests.test_utils: remove

This removes the test, which was only importing the file, and didn't contain any test cases.
```

2020-08-29 22:55 UTC, GuillaumeSeren commented
> Please change the commit message to:

Done !

2020-09-06 12:24 UTC, flokli approved these changes

2020-09-06 12:24 UTC, merged